[package]
name = "autocomplete"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.32.1"
serde = { version = "1.0.210", features = ["derive"]}
serde_bare = "0.5.0"
serde_json = "1.0.128"
# sqlite = "0.36.1"
